name: scanmyblood
description: "Blood Group App with Offline + Online AI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:

  flutter:

    sdk: flutter
  tflite_flutter: ^0.10.0
  image: ^4.0.17
  connectivity_plus: ^4.0.2
  http: ^1.1.0
  image_picker: ^0.8.7+5
  intl_phone_field: ^3.2.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  url_launcher: ^6.3.0
  share_plus: ^11.0.0
  sqflite: ^2.3.3
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  badges: ^3.1.2
  intl: ^0.20.1
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/ur.json
    - assets/lang/logo.png
    - assets/lang/search_donor.png
    - assets/lang/badge.png